---
- hosts: rocky
  become: true
  tasks:

  - name: update repository   
    dnf:
      update_cache: yes 

  - name: install httpd package
    dnf:
     name: httpd
     state: latest
  - name: add php for httpd
    dnf:
      name: php
      state: latest
