---
- hosts: all
  become: true
  tasks:

    - name: Update package cache for RHEL-based systems (Rocky/CentOS)
      dnf:
        update_cache: yes
      when: ansible_os_family == "RedHat"

    - name: Update package cache for Debian-based systems (Ubuntu)
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install httpd (Apache) on Rocky/CentOS
      dnf:
        name: httpd
        state: latest
      when: ansible_distribution in ["Rocky", "CentOS"]

    - name: Install apache2 on Ubuntu
      apt:
        name: apache2
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: Install PHP on Rocky/CentOS
      dnf:
        name: php
        state: latest
      when: ansible_distribution in ["Rocky", "CentOS"]

    - name: Install PHP on Ubuntu
      apt:
        name: php
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: Ensure Apache is started and enabled (RHEL-based)
      service:
        name: httpd
        state: started
        enabled: true
      when: ansible_distribution in ["Rocky", "CentOS"]

    - name: Ensure Apache is started and enabled (Ubuntu)
      service:
        name: apache2
        state: started
        enabled: true
      when: ansible_distribution == "Ubuntu"

